# Generated by Django 4.2.5 on 2023-09-09 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(choices=[('Ford', 'Ford'), ('Toyota', 'Toyota'), ('Honda', 'Honda'), ('VW', 'Volkswagen'), ('BMW', 'BMW'), ('MB', 'Mercedes-Benz'), ('Chevy', 'Chevrolet'), ('Nissan', 'Nissan'), ('Audi', 'Audi'), ('Hyundai', 'Hyundai'), ('Subaru', 'Subaru'), ('Kia', 'Kia'), ('Volvo', 'Volvo'), ('Jaguar', 'Jaguar'), ('Tesla', 'Tesla')], default='undefined', max_length=13, verbose_name='Marca')),
                ('tipoCombustivel', models.CharField(choices=[('Gasol', 'Gasolinha'), ('alco', 'Alcool'), ('Flex', 'Flex')], default='Flex', max_length=20, verbose_name='Tipo Combustivel')),
                ('modelo', models.CharField(max_length=50, verbose_name='modelo')),
                ('ano', models.DateField(verbose_name='Ano Do Modelo')),
                ('cambio', models.BooleanField(default=True, verbose_name='Tipo De Cambio')),
                ('categoria', models.CharField(max_length=10, verbose_name='Categoria Carro')),
            ],
        ),
        migrations.CreateModel(
            name='carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=7, unique=True, verbose_name='Placa')),
                ('quilometragem', models.CharField(max_length=7, verbose_name='Quilometragem')),
                ('ultimaRevisao', models.DateField(verbose_name='Ultima Revisao')),
                ('status', models.BooleanField(default=False, verbose_name='Status Do Veiculo')),
                ('preco', models.IntegerField(verbose_name='Preco Do Veiculo')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anunciarVeiculo.veiculo')),
            ],
        ),
    ]
