# Generated by Django 4.2.4 on 2023-09-08 19:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('senha', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='O número de telefone deve ter 10 dígitos (apenas números).', regex='^\\d{10}$')], verbose_name='Telefone')),
                ('endereco', models.CharField(max_length=300)),
            ],
        ),
    ]
