# Generated by Django 4.2.5 on 2023-09-13 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anunciarVeiculos', '0006_rename_modelo_modelo_model_alter_veiculo_veiculo'),
        ('solicitarAnuncio', '0001_initial'),
        ('login', '0003_alter_usuario_telefone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuario',
            new_name='Cliente',
        ),
    ]
