# Generated by Django 4.2.5 on 2023-09-19 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_cadastro'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cadastro',
        ),
    ]
