# Generated by Django 4.2.5 on 2023-11-20 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listaDesejos', '0001_initial'),
        ('login', '0008_delete_cadastro'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='lista',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='listaDesejos.lista'),
        ),
    ]
