# Generated by Django 4.2.5 on 2023-12-04 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_cliente_lista'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='lista',
        ),
    ]
