# Generated by Django 4.2.5 on 2023-12-09 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_remove_cliente_lista'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='imgBanner',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='imgPerfil',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
