# Generated by Django 4.2.4 on 2023-09-12 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0002_usuario_delete_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=50, verbose_name='Modelo')),
                ('ano', models.CharField(max_length=4, verbose_name='Ano')),
                ('quilometragem', models.CharField(max_length=6, verbose_name='Quilometragem')),
                ('cambio', models.BooleanField(default=False, verbose_name='Automático')),
                ('data', models.DateField(auto_now_add=True, verbose_name='Data')),
                ('servico', models.BooleanField(default=False, verbose_name='Alugar?')),
                ('tipocombust', models.CharField(choices=[('Gasol', 'Gasolina'), ('alco', 'Alcool'), ('Flex', 'Flex')], default='Undefined', max_length=20, verbose_name='Combustível')),
                ('solicitante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.usuario', verbose_name='Solicitante')),
            ],
        ),
    ]
