# Generated by Django 4.2.5 on 2023-09-18 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitarAnuncio', '0003_alter_solicitacao_solicitante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao',
            name='tipocombust',
            field=models.CharField(choices=[('Gasol', 'Gasolina'), ('alco', 'Alcool'), ('Flex', 'Flex'), ('Hibrid', 'Híbrido'), ('eletric', 'Elétrico')], default='Undefined', max_length=20, verbose_name='Combustível'),
        ),
    ]
