# Generated by Django 4.2.5 on 2023-10-13 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitarAnuncio', '0005_alter_solicitacao_tipocombust'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitacao',
            name='tipocombust',
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='combustivel',
            field=models.CharField(default='Gasolina', max_length=50, verbose_name='Combustível'),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='situacao',
            field=models.BooleanField(default=False, verbose_name='Situação'),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='cambio',
            field=models.CharField(max_length=50, verbose_name='Câmbio'),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='data',
            field=models.CharField(max_length=50, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='servico',
            field=models.BooleanField(default=False, verbose_name='Serviço'),
        ),
    ]
