# Generated by Django 4.2.5 on 2023-10-25 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_delete_cadastro'),
        ('solicitarAnuncio', '0006_remove_solicitacao_tipocombust_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao',
            name='data',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='solicitante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.cliente', to_field='cpf', verbose_name='Solicitante'),
        ),
    ]
