# Generated by Django 4.2.5 on 2023-10-26 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_delete_cadastro'),
        ('solicitarAnuncio', '0007_alter_solicitacao_data_alter_solicitacao_solicitante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao',
            name='solicitante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.cliente', verbose_name='Solicitante'),
        ),
    ]
