# Generated by Django 4.2.5 on 2023-10-31 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitarAnuncio', '0008_alter_solicitacao_solicitante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao',
            name='servico',
            field=models.CharField(max_length=50, verbose_name='Serviço'),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='situacao',
            field=models.CharField(max_length=50, verbose_name='Situação'),
        ),
    ]
