# Generated by Django 4.2.5 on 2023-12-05 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anunciarVeiculos', '0023_alter_anuncio_descricao_alter_anuncio_img1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_comprador', models.CharField(max_length=200, verbose_name='Nome completo do comprador')),
                ('cpf_comprador', models.CharField(max_length=11, verbose_name='CPF')),
                ('data', models.DateField(auto_now_add=True)),
                ('valor', models.IntegerField(verbose_name='Preço pago')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anunciarVeiculos.veiculo', verbose_name='Placa do veículo comprado')),
            ],
        ),
    ]
