# Generated by Django 4.2.5 on 2023-12-05 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venderVeiculos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='veiculo',
        ),
        migrations.AddField(
            model_name='venda',
            name='ano',
            field=models.IntegerField(null=True, verbose_name='Ano'),
        ),
        migrations.AddField(
            model_name='venda',
            name='contato',
            field=models.CharField(max_length=100, null=True, verbose_name='Contato do comprador'),
        ),
        migrations.AddField(
            model_name='venda',
            name='cor',
            field=models.CharField(max_length=100, null=True, verbose_name='Cor'),
        ),
        migrations.AddField(
            model_name='venda',
            name='marca',
            field=models.CharField(max_length=100, null=True, verbose_name='Marca'),
        ),
        migrations.AddField(
            model_name='venda',
            name='modelo',
            field=models.CharField(max_length=100, null=True, verbose_name='Modelo'),
        ),
    ]
