# Generated by Django 4.2.4 on 2023-09-12 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anunciarVeiculos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='descricao',
            field=models.TextField(max_length=300, verbose_name='Descricao'),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='img1',
            field=models.CharField(max_length=100, verbose_name='Imagem um'),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='img2',
            field=models.CharField(max_length=100, verbose_name='Imagem dois'),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anunciarVeiculos.veiculo', verbose_name='Veiculo'),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='marca',
            field=models.CharField(max_length=20, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='modelo',
            field=models.CharField(max_length=50, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='qtdPortas',
            field=models.IntegerField(verbose_name='Quantidade de portas'),
        ),
    ]
