# Generated by Django 4.2.5 on 2023-09-13 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anunciarVeiculos', '0005_remove_veiculo_ultimarevisao_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelo',
            old_name='modelo',
            new_name='model',
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anunciarVeiculos.modelo', verbose_name='Modelo/Marca'),
        ),
    ]
