# Generated by Django 4.2.5 on 2023-09-15 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('anunciarVeiculos', '0006_rename_modelo_modelo_model_alter_veiculo_veiculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='dono',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Dono'),
        ),
    ]
