# Generated by Django 4.2.5 on 2023-09-16 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anunciarVeiculos', '0007_alter_veiculo_dono'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='cor',
            field=models.CharField(default='undefined', max_length=50, verbose_name='Cor'),
        ),
    ]
