# Generated by Django 4.2.5 on 2023-09-18 17:21

import anunciarVeiculos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anunciarVeiculos', '0009_alter_veiculo_dono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelo',
            name='ano',
            field=models.DateField(help_text='A data deve ter no máximo 4 dígitos', validators=[anunciarVeiculos.models.Modelo.validar_data], verbose_name='Ano Do Modelo'),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='tipoCombustivel',
            field=models.CharField(choices=[('Gasol', 'Gasolina'), ('alco', 'Alcool'), ('Flex', 'Flex'), ('Hibrid', 'Híbrido'), ('eletric', 'Elétrico')], default='Undefined', max_length=20, verbose_name='Tipo Combustível'),
        ),
    ]
