# Generated by Django 4.2.5 on 2023-09-18 20:48

import anunciarVeiculos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anunciarVeiculos', '0010_alter_modelo_ano_alter_modelo_tipocombustivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelo',
            name='ano',
            field=models.PositiveIntegerField(help_text='A data deve ter no máximo 4 dígitos', validators=[anunciarVeiculos.models.Modelo.validar_data], verbose_name='Ano Do Modelo'),
        ),
    ]
