# Generated by Django 4.2.5 on 2023-09-18 21:02

import anunciarVeiculos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anunciarVeiculos', '0011_alter_modelo_ano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelo',
            name='ano',
            field=models.PositiveIntegerField(help_text='O ano deve ter no máximo 4 dígitos', validators=[anunciarVeiculos.models.Modelo.validar_data], verbose_name='Ano'),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='cambio',
            field=models.BooleanField(default=True, verbose_name='Automático'),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='categoria',
            field=models.CharField(choices=[('comp', 'Compacto'), ('seda', 'Sedan'), ('suv', 'SUV'), ('hatch', 'Hatchback'), ('picap', 'Picape'), ('esport', 'Esportivo')], default='Undefined', max_length=40, verbose_name='Categoria'),
        ),
    ]
