# Generated by Django 4.2.5 on 2023-09-18 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anunciarVeiculos', '0012_alter_modelo_ano_alter_modelo_cambio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelo',
            name='categoria',
            field=models.CharField(choices=[('compacto', 'Compacto'), ('sedan', 'Sedan'), ('suv', 'SUV'), ('hatchback', 'Hatchback'), ('picape', 'Picape'), ('esportivo', 'Esportivo')], default='Undefined', max_length=40, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='tipoCombustivel',
            field=models.CharField(choices=[('gasolina', 'Gasolina'), ('alcool', 'Alcool'), ('flex', 'Flex'), ('hibrido', 'Híbrido'), ('eletrico', 'Elétrico')], default='Undefined', max_length=20, verbose_name='Tipo Combustível'),
        ),
    ]
