# Generated by Django 4.2.5 on 2023-10-13 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anunciarVeiculos', '0013_alter_modelo_categoria_alter_modelo_tipocombustivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='destaque',
            field=models.BooleanField(default=False, verbose_name='Destaque'),
        ),
    ]
