# Generated by Django 4.2.6 on 2023-10-18 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anunciarVeiculos', '0014_anuncio_destaque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='pontos',
            field=models.IntegerField(default=0, verbose_name='Pontos'),
        ),
    ]
