# Generated by Django 4.2.6 on 2023-10-18 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anunciarVeiculos', '0015_alter_anuncio_pontos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='veiculo',
            old_name='veiculo',
            new_name='modelo',
        ),
    ]
