# Generated by Django 4.2.5 on 2023-10-23 21:19

import anunciarVeiculos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anunciarVeiculos', '0017_remove_veiculo_servico_anuncio_preco_anuncio_servico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='img1',
            field=models.ImageField(blank=True, null=True, upload_to=anunciarVeiculos.models.upload_image, verbose_name='Imagem um'),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to=anunciarVeiculos.models.upload_image, verbose_name='Imagem dois'),
        ),
    ]
