# Generated by Django 4.2.5 on 2023-10-23 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anunciarVeiculos', '0018_alter_anuncio_img1_alter_anuncio_img2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='modelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anunciarVeiculos.modelo', verbose_name='Modelo'),
        ),
    ]
