# Generated by Django 4.2.5 on 2023-10-25 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_delete_cadastro'),
        ('anunciarVeiculos', '0020_remove_veiculo_preco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anunciarVeiculos.veiculo', to_field='placa', verbose_name='Veiculo'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='dono',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.cliente', to_field='cpf', verbose_name='Dono'),
        ),
    ]
