# Generated by Django 4.2.5 on 2023-10-26 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_delete_cadastro'),
        ('anunciarVeiculos', '0021_alter_anuncio_veiculo_alter_veiculo_dono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anunciarVeiculos.veiculo', verbose_name='Veiculo'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='dono',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.cliente', verbose_name='Dono'),
        ),
    ]
