# Generated by Django 4.2.5 on 2023-10-29 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anunciarVeiculos', '0022_alter_anuncio_veiculo_alter_veiculo_dono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='descricao',
            field=models.TextField(max_length=500, verbose_name='Descricao'),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='img1',
            field=models.CharField(max_length=500, null=True, verbose_name='Imagem um'),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='img2',
            field=models.CharField(max_length=500, null=True, verbose_name='Imagem dois'),
        ),
    ]
