# Generated by Django 4.2.5 on 2023-12-07 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anunciarVeiculos', '0023_alter_anuncio_descricao_alter_anuncio_img1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='data_expiracao_destaque',
            field=models.DateField(null=True, verbose_name='Data de expiração do destaque'),
        ),
    ]
