# Generated by Django 4.2.5 on 2023-10-31 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alugarVeiculo', '0004_alter_alugar_cliente_alter_alugar_veiculo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alugar',
            name='dataDev',
        ),
        migrations.RemoveField(
            model_name='alugar',
            name='dataInicio',
        ),
    ]
