# Generated by Django 4.2.5 on 2023-12-06 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alugarVeiculo', '0005_remove_alugar_datadev_remove_alugar_datainicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='alugar',
            name='dataDev',
            field=models.CharField(max_length=200, null=True, verbose_name='Data de devolução'),
        ),
        migrations.AddField(
            model_name='alugar',
            name='dataInicio',
            field=models.CharField(max_length=200, null=True, verbose_name='Data da retirada'),
        ),
        migrations.AddField(
            model_name='alugar',
            name='hora_retirada',
            field=models.CharField(max_length=200, null=True, verbose_name='Hora da retirada'),
        ),
    ]
