# Generated by Django 4.2.5 on 2023-11-20 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anunciarVeiculos', '0023_alter_anuncio_descricao_alter_anuncio_img1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelos', models.ManyToManyField(to='anunciarVeiculos.modelo')),
            ],
        ),
    ]
