# Generated by Django 4.2.5 on 2023-10-14 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0008_delete_cadastro'),
        ('anunciarVeiculos', '0014_anuncio_destaque'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data da visita')),
                ('horario', models.TimeField(verbose_name='Hora da visita')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.cliente', verbose_name='Cliente')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anunciarVeiculos.veiculo', verbose_name='Veiculo Reservado')),
            ],
        ),
    ]
