# Generated by Django 4.2.5 on 2023-10-25 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anunciarVeiculos', '0021_alter_anuncio_veiculo_alter_veiculo_dono'),
        ('login', '0008_delete_cadastro'),
        ('reservarVeiculos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.cliente', to_field='cpf', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anunciarVeiculos.veiculo', to_field='placa', verbose_name='Veiculo Reservado'),
        ),
    ]
