# Generated by Django 4.2.5 on 2023-10-31 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservarVeiculos', '0003_alter_reserva_cliente_alter_reserva_veiculo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='data',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='horario',
        ),
    ]
