# Generated by Django 4.2.5 on 2023-12-06 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservarVeiculos', '0004_remove_reserva_data_remove_reserva_horario'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='data',
            field=models.CharField(max_length=200, null=True, verbose_name='Data da Visita'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='hora',
            field=models.CharField(max_length=200, null=True, verbose_name='Hora da visita'),
        ),
    ]
